# Generated by Django 4.2 on 2023-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsyakApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalmodels',
            name='Zuhur',
            field=models.TimeField(default='05:19:00'),
        ),
    ]
